# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client/ui/src/sensor_create.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SensorCreate(object):
    def setupUi(self, SensorCreate):
        SensorCreate.setObjectName("SensorCreate")
        SensorCreate.resize(543, 207)
        self.context = QtWidgets.QVBoxLayout(SensorCreate)
        self.context.setContentsMargins(0, 0, 0, 0)
        self.context.setSpacing(10)
        self.context.setObjectName("context")
        self.title = QtWidgets.QLabel(SensorCreate)
        self.title.setMinimumSize(QtCore.QSize(400, 20))
        self.title.setMaximumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.context.addWidget(self.title)
        self.form = QtWidgets.QWidget(SensorCreate)
        self.form.setObjectName("form")
        self.gridLayout = QtWidgets.QGridLayout(self.form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.name = QtWidgets.QLineEdit(self.form)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 0, 1, 2)
        self.title_port = QtWidgets.QLabel(self.form)
        self.title_port.setObjectName("title_port")
        self.gridLayout.addWidget(self.title_port, 2, 1, 1, 1)
        self.model = QtWidgets.QComboBox(self.form)
        self.model.setObjectName("model")
        self.gridLayout.addWidget(self.model, 3, 0, 1, 1)
        self.title_name = QtWidgets.QLabel(self.form)
        self.title_name.setObjectName("title_name")
        self.gridLayout.addWidget(self.title_name, 0, 0, 1, 1)
        self.title_model = QtWidgets.QLabel(self.form)
        self.title_model.setObjectName("title_model")
        self.gridLayout.addWidget(self.title_model, 2, 0, 1, 1)
        self.port = QtWidgets.QComboBox(self.form)
        self.port.setEditable(True)
        self.port.setObjectName("port")
        self.gridLayout.addWidget(self.port, 3, 1, 1, 1)
        self.confirm = QtWidgets.QPushButton(self.form)
        self.confirm.setObjectName("confirm")
        self.gridLayout.addWidget(self.confirm, 4, 0, 1, 1)
        self.cancel = QtWidgets.QPushButton(self.form)
        self.cancel.setFlat(True)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 4, 1, 1, 1)
        self.context.addWidget(self.form)

        self.retranslateUi(SensorCreate)
        QtCore.QMetaObject.connectSlotsByName(SensorCreate)

    def retranslateUi(self, SensorCreate):
        _translate = QtCore.QCoreApplication.translate
        SensorCreate.setWindowTitle(_translate("SensorCreate", "添加传感器"))
        self.title.setText(_translate("SensorCreate", "添加传感器"))
        self.title_port.setText(_translate("SensorCreate", "端口"))
        self.title_name.setText(_translate("SensorCreate", "名称"))
        self.title_model.setText(_translate("SensorCreate", "型号"))
        self.confirm.setText(_translate("SensorCreate", "确定"))
        self.cancel.setText(_translate("SensorCreate", "取消"))
