# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client/ui/src/sensor_field.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SensorField(object):
    def setupUi(self, SensorField):
        SensorField.setObjectName("SensorField")
        SensorField.resize(400, 200)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SensorField)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.view = QtWidgets.QWidget(SensorField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view.sizePolicy().hasHeightForWidth())
        self.view.setSizePolicy(sizePolicy)
        self.view.setMinimumSize(QtCore.QSize(100, 0))
        self.view.setObjectName("view")
        self.view_layout = QtWidgets.QVBoxLayout(self.view)
        self.view_layout.setSpacing(0)
        self.view_layout.setObjectName("view_layout")
        self.name = QtWidgets.QLabel(self.view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.view_layout.addWidget(self.name)
        self.value = QtWidgets.QLabel(self.view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value.sizePolicy().hasHeightForWidth())
        self.value.setSizePolicy(sizePolicy)
        self.value.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.value.setFont(font)
        self.value.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.value.setObjectName("value")
        self.view_layout.addWidget(self.value)
        self.unit = QtWidgets.QLabel(self.view)
        self.unit.setMinimumSize(QtCore.QSize(100, 0))
        self.unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.unit.setObjectName("unit")
        self.view_layout.addWidget(self.unit)
        self.horizontalLayout.addWidget(self.view)
        self.trend = QtWidgets.QVBoxLayout()
        self.trend.setObjectName("trend")
        self.status = QtWidgets.QLabel(SensorField)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.status.setFont(font)
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.trend.addWidget(self.status)
        self.horizontalLayout.addLayout(self.trend)

        self.retranslateUi(SensorField)
        QtCore.QMetaObject.connectSlotsByName(SensorField)

    def retranslateUi(self, SensorField):
        _translate = QtCore.QCoreApplication.translate
        SensorField.setWindowTitle(_translate("SensorField", "传感器指标"))
        self.name.setText(_translate("SensorField", "名称"))
        self.value.setText(_translate("SensorField", "9.99"))
        self.unit.setText(_translate("SensorField", "单位"))
        self.status.setText(_translate("SensorField", "状态"))
